---
title: "Basic NonLinear Mixed Effect Example"
author: "Ruben Cabrera"
date: "2023-08-01"
output: 
  github_document: default
  html_document: default
# always_allow_html: true
# devtools::install_github("kupietz/kableExtra")
# install.packages("xfun", repos=c("http://rstudio.org/_packages", "http://cran.rstudio.com"))
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Basic Example

Basic Example

https://www.youtube.com/watch?v=eGSVcrkd6yU

```{r, message=FALSE, warning=FALSE}

library(nlme)
#library(lmerTest)
library(ggplot2)
library(dplyr) # For filter
library(lattice)
# install.packages("sjPlot")
#library(sjPlot) # To use plot_model

```

## Data

```{r data}
rm(list = ls())

n=4 # Number of subjects
time=c(10,20,40,60,80,100,120,140)
y1=c(120.8,101.2,64.7,43.2,32.0,19.9,11.9,10.1)
y2=c(140.7,110.8,75.9,49.2,32.5,21.5,17.9,11.8)
y3=c(74.7,61.1,42.2,28.5,15.1,8.1,7.0,5.8)
y4=c(89.1,74.0,46.7,31.2,22.0,14.3,9.4,4.8)
y=c(y1,y2,y3,y4)
Sex=factor(c(rep(c(0,1),c(16,16)))) # 0 = Woman, 1 = Man
t=c(rep(time,4))
Subject=factor(rep(c(1,2,3,4),c(8,8,8,8)))

df = data.frame(y,Subject,Sex,t)

```


## Plot data

```{r plotdata}
ggplot(df, aes(x = t, y = y, group = Subject, color = Sex)) + geom_line()+ geom_point() + xlab('Weeks')

```

## Models 1-4: y1 to y4

```{r model1}
M1 <- nls(y1 ~ Y0 * exp(-k*time), start = list(Y0=100,k=0.02))
M1
M2 <- nls(y2 ~ Y0 * exp(-k*time), start = list(Y0=100,k=0.02))
M2
M3 <- nls(y3 ~ Y0 * exp(-k*time), start = list(Y0=100,k=0.02))
M3
M4 <- nls(y4 ~ Y0 * exp(-k*time), start = list(Y0=100,k=0.02))
M4
```
# Plots Models 1-4: y1 to y4

```{r M1_plots}

# Residuals vs Fitted
plot(M1, which = 1)
plot(M2, which = 1)
plot(M3, which = 1)
plot(M4, which = 1)


# Plot general fit

# Extract fitted values
df$fittedM1 <- fitted(M1)
df$fittedM2 <- fitted(M2)
df$fittedM3 <- fitted(M3)
df$fittedM4 <- fitted(M4)

# Plot fitted

ggplot(df, aes(x = t, y = y, color = Subject)) +
  geom_point() +
  geom_line(aes(y = fittedM1, color = "pink")) + 
  geom_line(aes(y = fittedM2, color = "green")) +
  geom_line(aes(y = fittedM3, color = "cyan")) +
  geom_line(aes(y = fittedM4, color = "purple")) +
  labs(title = "Fitted Values for Each Subject", x = "time", y = "y")

```
# Model 5: y ~ y0 * exp(-k*t)

```{r model5}
M5 <- nls(y ~ Y0*exp(-k*t), start=c(Y0=100,k=0.02))
summary(M5)
```

# Plots Model M5:  y ~ y0 * exp(-k*t)

```{r M5_plots}
# Residuals vs Fitted
plot(M5, which = 1)

# Extract fitted values
df$fittedM5 <- fitted(M5)

# Plot fitted

ggplot(df, aes(x = t, y = y, color = Subject)) +
  geom_point() +
  geom_line(aes(y = fittedM5)) +
  labs(title = "Fitted Values for Each Subject", x = "time", y = "y")
```



# Model 6: y ~ y0 * exp(-k * t)

```{r model6}
gd <- groupedData(y~t|Subject,data=df)
M6 <- nlme(y ~ y0*exp(-k*t), data = gd, 
           random=y0~1,
           fixed=y0+k~1,
           start = c(y0=100,k=0.02))
M6
random.effects(M6)  # ranefe(M6)
```

# Plots Model M6: y ~ y0 * exp(-k * t)

```{r M6_plots}
##
plot(t,y,col=Subject,ylim=c(0,160),xlim=c(0,140),xlab="Time (min)",ylab = "Conc.(mg/L)",las=1,pch=as.numeric(Sex))
legend("topright",c("Ind.1","Ind.2","Ind.3","Ind.4"),pch=c(1,1,2,2),col=1:4)


tt=seq(0,140)
y0r=M6$coefficients$random$Subject
y0r=y0r[order(as.numeric(row.names(y0r))),,drop=F]
y0f=M6$coefficients$fixed[1]
k1=M6$coefficients$fixed[2]
for(i in 1:n){
  yp=(y0f+y0r[i])*exp(-k1*tt)
  lines(tt,yp,col=i)
}
```


# Model 7: 

```{r model7}
M7 <- nlme(y ~ y0*exp(-k*t), data = gd, 
           random=y0~1,
           fixed=c(y0~1+Sex,k~1),
           start = c(y0=100,Sex=0,k=0.02))
M7
random.effects(M7)  # ranefe(M7)
```

# Plots Model M7: 

```{r M7_plots}
##
plot(t,y,col=Subject,ylim=c(0,160),xlim=c(0,140),xlab="Time (min)",ylab = "Conc.(mg/L)",las=1,pch=as.numeric(Sex))
legend("topright",c("Ind.1","Ind.2","Ind.3","Ind.4"),pch=c(1,1,2,2),col=1:4)


tt=seq(0,140)
yW=M7$coefficients$fixed[1]
yM=M7$coefficients$fixed[1]+M7$coefficients$fixed[2]
k =M7$coefficients$fixed[3]

yW=(yW)*exp(-k*tt)
lines(tt,yW,col=i)

yM=(yM)*exp(-k*tt)
lines(tt,yM,col=i)
  
```
# Anova M6 y M7: 

```{r anova_M6_M7}
##
anova(M6,M7)
  
```


# Model 8: 

```{r model8}
M8 <- nlme(y ~ y0*exp(-k*t), data = gd, 
           random=y0 + k ~ 1,
           fixed=y0 + k ~ 1,
           start = c(y0=100,k=0.02))
M8
random.effects(M8)  # ranefe(M8)
summary(M8)
```


```{r M8_plots}
##
plot(t,y,col=Subject,ylim=c(0,160),xlim=c(0,140),xlab="Time (min)",ylab = "Conc.(mg/L)",las=1,pch=as.numeric(Sex))
legend("topright",c("Ind.1","Ind.2","Ind.3","Ind.4"),pch=c(1,1,2,2),col=1:4)


tt=seq(0,140)
y0r=M8$coefficients$random$Subject
y0r=y0r[order(as.numeric(row.names(y0r))),,drop=F]
y0f=M8$coefficients$fixed[1]
k1=M8$coefficients$fixed[2]
for(i in 1:n){
  yp=(y0f+y0r[i,1])*exp(-(k1+y0r[i,2])*tt)
  lines(tt,yp,col=i)
}
```
